### ISSUE TITLE
Build Error on Arch Linux

### ISSUE THREAD

**Issue by cleonyc** [martijnmichel/nordvpn-linux#2]
When I run `quasar build`, I get the error:
```
ERROR in ./node_modules/node-pty/build/Release/pty.node 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/node-pty/lib/index.js 49:49-85
 @ ./src/boot/xterm.js
 @ ./.quasar/client-entry.js
 @ multi ./.quasar/client-entry.js
```
I tried running `yarn run lint`, but that didn't seem to do anything.

**Comment by martijnmichel** [comment]
Do you have quasar installed globally?
Else.. try rebuilding node-pty, ive included a little npm script: npm run rebuild

**Comment by martijnmichel** [comment]
Oh, i just figured, you need to quasar dev (or build) -m electron

**Comment by cleonyc** [comment]
Thanks! It worked! I initially ran into an error, but ran your npm script and it fixed it. Also, I'm going to package this for the AUR. What should I call it? nordvpn-linux?

**Comment by martijnmichel** [comment]
Great.
Well.. i just created a release with AppImage and snap binaries. So not sure it's needed to put it on AUR, on the other hand it'll give some exposure. Can we maintain it together? 
nordvpn-linux will be fine yes.

**Comment by cleonyc** [comment]
Sure! Sounds great!

**Comment by zlnvch** [comment]
It seems it's still not up on the AUR. Would be really nice to see it on there.
